version: '3'
services:
  railsapp:
    build: ./rails-app/
    command: sh -c "cd ./rails-app && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"

  assetsserver:
    build: ./micro-fronts/
    command: sh -c "http-server ./micro-fronts --cors"
    volumes:
      - .:/assets
    ports:
      - "8080:8080"
